def get_desired_caps():
    desired_cap = {'project': 'Intrepid Percy',
                   'build': 'Basic Percy Test',
                   'os': 'Windows',
                   'os_version': '10',
                   'browser': 'Chrome',
                   'browser_version': 'latest',
                   'browserstack.use_w3c': 'true',
                   }
    return desired_cap

def get_snapshots_to_take():
    # Set this to True to take snapshots of all pages
    TakeSnapshots = False
    
    snapshots_to_take = {
        'Login Page': TakeSnapshots,
        'Forgot PW': TakeSnapshots,
        'Splash Page': TakeSnapshots,
        'Home Page': TakeSnapshots,
        'FAQ Page': TakeSnapshots,
        'Contact Page': TakeSnapshots,
        'Mission Page': TakeSnapshots,
        'Learning Path Page': TakeSnapshots,
        'Learning Path Modal': TakeSnapshots,
        'Multicat Page': TakeSnapshots,
        'Mission Share Step': TakeSnapshots,
        'Mission File Upload Step': TakeSnapshots,
        'Mission MOV Upload Step': TakeSnapshots,
        'Mission MP4 Upload Step': TakeSnapshots,
        'Mission Image Step': TakeSnapshots,
        'Text List Step': TakeSnapshots,
        'Text Field Step': TakeSnapshots,
        'Message Prompt Step': TakeSnapshots,
        'Project Intro': TakeSnapshots,
        'Project Modal': TakeSnapshots,
        'Content Descriptions': TakeSnapshots,
        'Custom Content': TakeSnapshots,
        'Multicat2': TakeSnapshots,
        'Audio': TakeSnapshots,
        'Context': TakeSnapshots,
        'Document': TakeSnapshots,
        'External Link': TakeSnapshots,
        'Quiz Intro': TakeSnapshots,
        'Quiz Step 1 Answered': TakeSnapshots,
        'Quiz Step 2 Answered': TakeSnapshots,
        'Quiz Step 3 Answered': TakeSnapshots,
        'Quiz Step 4 Answered A': TakeSnapshots,
        'Quiz Step 4 Answered B': TakeSnapshots,
        'Quiz Step 5 Answered A': TakeSnapshots,
        'Quiz Step 5 Answered B': TakeSnapshots,
        'Quiz Step 6': TakeSnapshots,
        'Quiz Step 7': TakeSnapshots,
        'Quiz Complete': TakeSnapshots,
        'Account Menu': TakeSnapshots,
        'My Profile': TakeSnapshots,
        'Account Settings': TakeSnapshots,
        'Announcements': TakeSnapshots,
        'Search All Results': TakeSnapshots,
        'Search Class Content': TakeSnapshots,
        'Search Community Content': TakeSnapshots,
        'Search People': TakeSnapshots,
        'GWS Page': TakeSnapshots,
        'Timeline Page': TakeSnapshots,
        'Leaderboard Page': TakeSnapshots,
        'Content Page 1': TakeSnapshots,
        'Content Page 2': TakeSnapshots,
        '404 Not Found Page': TakeSnapshots,
    }
    return snapshots_to_take
